version: '3.8'
services:
  app:
    build: .
    ports:
      - "5080:5007" # Map host port 5080 to container port 5007
    environment:
      - NODE_ENV=production
      - PORT=5007
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
    volumes:
      - ./.env:/app/.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5007/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - app-network
networks:
  app-network:
    driver: bridge